artifact_location: /home/franco/Documents/Github/Platzi/MLops_MVP/tracking/~/Documents/Github/Platzi/MLops_MVP/tracking/experiment_ml/0
creation_time: 1746908509231
experiment_id: '0'
last_update_time: 1746908509231
lifecycle_stage: active
name: Default
