artifact_location: /home/franco/Documents/Github/Platzi/MLops_MVP/tracking/~/Documents/Github/Platzi/MLops_MVP/tracking/experiment_ml/131268167226052742
creation_time: 1746908612695
experiment_id: '131268167226052742'
last_update_time: 1746908612695
lifecycle_stage: active
name: iris_experiment_ml_local
